### PR TITLE
Ippc2023

### PR DESCRIPTION
**Pull request by ataitler**

### CODE REVIEW

**Comment by ssanner** [comment]
Can we refactor the location of these competition instances?  Considering
that (a) the directory path "pyRDDLGym/Examples/" does not clearly indicate
that these are the competition instances -- and Examples are always prone
to get updated or augmented -- and (b) hopefully there will be future
competitions, can we move copies of these actual competition
domains/instances into a separate folder, perhaps under
"pyRDDLGym/Competitions/IPPC2023" that allows us to add other competition
directories in the future?  -Scott

**Comment by haz** [comment]
Isn't there already another repo for rddl instances?

**Comment by haz** [comment]
https://github.com/ataitler/rddlrepository/tree/main/rddlrepository%2FArchive%2FCompetitions

**Comment by ataitler** [comment]
yes of course, you guys are quick.
The competition instances will be moved to the rddlrepository. The IPPC branch also had code update in addition to the instances (which were needed there for the evaluation). 

Now that the competition is over, the instances will be moves, the rddlrepository will be updated, and we will also do some clean up and documentation.

**Comment by ataitler** [comment]
future competition instances should be placed in the rddlrepository directly without going through pyRDDLGym before.
The whole rapid development of the competition and the framework imposed some restrictions that are not natural. The framework and working on a competition should not be dependent.

**Pull request merged**
