### PR TITLE
Added files from IPC 2011, 2014, 2018

### PR DESCRIPTION
**Pull request by mike-gimelfarb**

### CODE REVIEW

**Comment by haz** [comment]
Kinda would like replication to be avoided if we can. All of the benchmarks are here...

https://github.com/AI-Planning/rddl-domains

...and will be plugged into the api.planning.domains initiative by the end of term.

**Comment by mike-gimelfarb** [comment]
I was under the impression we wanted to have past competition domains in separate folders. Do you prefer this to be under one directory? importing them using the ExampleManager/RDDLEnv should not make a difference since you would just refer to elevators2011 or elevators2014 as example keys. I can remove duplicates.

**Comment by haz** [comment]
I'd advocate they don't appear at all in pyRDDLGym. Keep the "this is the archive of rddl" completely separate.

**Comment by haz** [comment]
Some examples make sense, but there should be fairly trivial ways to fetch any benchmark (or all IPPC 2018 benchmarks (or an individual instance (or all POMDP benchmarks (or ...)))) all very soon. The access is wrapped with this library...

https://github.com/AI-Planning/api-tools

...but can be done natively fairly easily (just json requests and wgets).

**Comment by mike-gimelfarb** [comment]
I agree that we should use a more streamlined approach. the ExampleManager in principle allows us to extract a specific instance of a benchmark, and the meta data about pomdp, continuous vs discrete, or any other keywords would be easy to add to the domain.info file. But since you pointed out a tool that already exists perhaps there is no need to reinvent the wheel. I am only wondering if this supports rddl or only pddl so far?

**Comment by mike-gimelfarb** [comment]
On second thought,  your structure is very similar. Is there a possibility of including the (default) viz for each domain in the api (e.g. to instruct how to instantiate it)? an alternative is to not have the viz info there at all, and let the user do it. I am not sure what is the best way...

**Comment by haz** [comment]
What's the format of the viz currently? Not the stuff I made for the course, is it?

The current API just covers classical at the moment, but I have a team of students working on their capstone project to touch things up. RDDL is a high priority for this term, so I expect it to be done over the next month or two.

As for the folder structure -- they're intentially flat. Idea is that the API lets you bundle what you need, and you can have simultaneous ontologies over the same benchmarks. Break it down by IPPC year, or mdp-vs-pomdp, or those with/without intermediate variables, or ... It's all just a different API call away to search + fetch locally.

**Comment by mike-gimelfarb** [comment]
We are working to integrate your fantastic viz into the framework, and if I recall there was an improved text viz as well.

For the current approach we use, the .info file in each subdirectory has the location of the default viz as <module>.<class> which is located inside the Viz folder of pyRDDLGym. it is by default the text viz. for the latter it would look like 

viz=TextViz.TextVisualizer

It really is not the best way to do things, I admit.

I'm wondering if the easiest way is just have the user do the regular git clone install of your domains repo linked above, then we can extract info as needed from the api.py files. A separate dictionary can be included in pyRDDLGym to handle the detection of a non-default viz. I am not sure if Scott intended to have things self-contained for pyRDDLGym or the extra dependency is acceptable. I can try this approach and see how it works.

**Comment by haz** [comment]
Ah, I think I see what you mean. Custom viz if it exists, and otherwise the command-line colour coding stuff for a set # of simulations.

The api.py files will disappear quite quickly -- all the data around the instances goes into the database, which lets us search for the right subset of things we care about. An example in classical planning is all problems with a small effective width (thus indicating it's simple to solve) but open bounds (thus indicating it's hard to solve optimally). Any interesting query over the stats of problems is what it should enable. Beyond just "fetch all the IPPC 2018 benchmarks".

I could probably elevate the api-tools to pip, which would let pyrddl bring it in as a dependency. That's a design decision for you + team, though. Would mean having quick pythonic access to the full rddl archive, but also add `planning.domains` to the executable `PATH`, and will probably only work on linux/mac environments :P . So certainly some pros/cons to consider. Maybe just the python API to access the archive is what I should expose...

**Comment by ssanner** [comment]
All,

I had asked for the archive of RDDL competition domains to be cloned under
PyRDDLGym.

planning.domains is a fantastic central archive, but I would like all
legacy RDDL content (including historical competition content) that we'll
continue to support to be under PyRDDLGym as a one-stop shop for all things
RDDL.

Thanks,
Scott

**Comment by mike-gimelfarb** [comment]
We definitely would want a maximally portable solution that works on windows too! And given how many of our current bugs stem from compatibility issues, this is certainly something we want to consider before making this jump. I think it could be optimal to keep the past competition results (at least for now, so we can begin testing the baselines), and once your socket for rddl is complete I can look into making that an optional dependency. Since the goal seems to be geared towards continuous domains for the competition, I suspect we will be adding a number of new domains over the legacy.

As for filtering by keywords, I really do like your approach (this was something I put on my todo list even before this conversation) , but is currently not on the critical path (better visualization and testing baselines certainly is!)

**Review by ataitler — APPROVED** [review]
1. If Examples folder is empty it should be removed.
2. Competition is not a valid name for a folder in the framework, it is a general framework and not a specific competition (certainly not past ones) oriented. these are just legacy domains, if there are multiple versions we can rename them as 'v1', 'v2' etc chronologically. 
3. RDDL as a name for the folder that holds all the domains and problems is not appropriate.

**Comment by mike-gimelfarb** [comment]
1. Examples is kept because we have some new domains there not part of previous competition (e.g. racecar, gym envs). we definitely should be careful not to remove them for now.
2. I renamed Competition -> Legacy 
3. RDDL -> Domains

**Comment by haz** [comment]
[**aside**: if you want to enable the `Discussions` functionality in the GitHub project, we can take the conversation over there]

Can you provide the core desire for access to the domains here, @ssanner ? One downside of including is that it conflates the pip'able project with the suite of RDDL domains. If it's truly one-stop-shop, then would that include community authored on publications? All future IPPC's? My student's assignment 4 submissions? ;)

Even if it's just IPPC, the payload can start to become large. Both from a git repo and pypi package perspective, it becomes cumbersome.

When there are multiple versions of the domains floating around, we start to face the uncertainty on which version is actually the canonical one. We already face that on the classical side (planning.domains, IPC website archives, git projects for IPC, the FD set, the FF set, ...). The api.planning.domains pillar was meant to address that, but [[alas](https://xkcd.com/927/)]

So if it's seamless access to past RDDL, I think we can still get that while maintaining one central spot that doesn't ship w/ pyrddl. Doesn't need to be a solution that hosts them exclusively over on `ai-planning` (if that's the concern), but having them hosted in one canonical location still seems to have a lot of merit in my mind.

**Comment by mike-gimelfarb** [comment]
I don't have the settings visible for this project, perhaps it's a rights issue. @ataitler can you enable this?

**Comment by ssanner** [comment]
I don't think it's unreasonable to have a historical record of the three
RDDL competitions from the past decade in the PyRDDLGym repo which
amounts to 3 competitions X 8 domains X 10 instances.   We'll eventually
add 2023 for this year.  These are arguably official reference domains and
the space required is not a concern.  I'm not arguing that every RDDL
domain should be stored in the repo.

I'll probably realize in a few more years that I'm completely wrong about
this decision for all of the reasons Christian has raised, but I would
appreciate it if others can defer to my preference on this decision for now.

I would request the directory structure:

- Domains/Examples
- Domains/Competition/2011
- Domains/Competition/2014
- Domains/Competition/2018

I think this structure makes it completely clear what is being stored under
"Competition" (which is the directory name I had suggested recently) and,
implicitly, why it is included.

Maybe there is a better name than "Examples", but I think it works for now
and we can refactor later if necessary.

Thanks,
Scott

**Pull request merged**
