### PR TITLE
Re structure examples

### PR DESCRIPTION
**Pull request by ataitler**

### CODE REVIEW

**Comment by mike-gimelfarb** [comment]
Everything looks good to me. My only question is whether it is ok to have spaces in the domain name in the info file? For example, will this work  on the command line ? (I guess it should with quotation marks...)

**Review by mike-gimelfarb — APPROVED** [review]
For domain name in the domain.info, is it better to have the spaces?

**Comment by mike-gimelfarb** [comment]
Go ahead and merge, we can fix this later. I am just glad to get rid of so many files in the main :)

**Comment by ataitler** [comment]
Oh for sure, It got messy. I also don't think it is much of a problem we do not support a CLI now, it is just parsing of argv...

If we decide to support CLI then we can easily make it compatible.

**Pull request merged**
