### PR TITLE
Renamed VEL to ACC in instance file to match domain and prevent issues

### PR DESCRIPTION
**Pull request by buvnswrn**

### CODE REVIEW

**Comment by mike-gimelfarb** [comment]
That indeed looks like a bug, albeit a minor one since we set the values in the instance to their default anyways (so those lines are strictly not needed). Thanks for pointing it out though, and if you come across any other bugs, please let us know!

**Comment by mike-gimelfarb** [comment]
For undefined pvariables initialized in the instance, I think we actually want to handle this more elegantly in the future by raising a warning.

**Review by ataitler — APPROVED** [review]
Nice catch, it is weird that an exception was not raised in this case. 
An issue was filed by Mike and will be addressed in the next version.
Thanks!

**Comment by buvnswrn** [comment]
> That indeed looks like a bug, albeit a minor one since we set the values in the instance to their default anyways (so those lines are strictly not needed). Thanks for pointing it out though, and if you come across any other bugs, please let us know!

Sure, will test it out and let you know. I'm looking forward to work more towards the UAV trajectory planning and if you guys have more examples in RDDL that is somehow related to UAV Trajectory planning or UAV inspection, please let me know so it would be useful for my thesis work.

**Pull request merged**
